/home/mabdallah/.conda/envs/trialmatchai/lib/python3.11/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/home/mabdallah/.conda/envs/trialmatchai/lib/python3.11/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 150333.48it/s]
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 791.12it/s]
2025-07-16 22:19:23,655 - INFO - Server started on localhost:18783
2025-07-16 22:19:58,353 - INFO - Connection accepted from ('127.0.0.1', 43844)
2025-07-16 22:19:58,353 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "ae359d59fbd91b79b8cac7ab1f66afbc91f6716227b6f73af5964a47.PubTator"}
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 13626.72it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 26921.08it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-07-16 22:23:26,080 - INFO - Connection accepted from ('127.0.0.1', 42682)
2025-07-16 22:23:26,081 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "e78efe64b067d7c6ebe4216819000751a7603e0892821caf88bbe57c.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 20440.08it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 7690.33it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-07-16 22:28:05,287 - INFO - Connection accepted from ('127.0.0.1', 39226)
2025-07-16 22:28:05,287 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "d8c0749b4cabbd5e7fa9c366d366170266a0289a6471006ccc4cce4e.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 9504.43it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 29392.46it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-07-16 22:33:00,752 - INFO - Connection accepted from ('127.0.0.1', 38380)
2025-07-16 22:33:00,752 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "99653b33f56427874f327320e5fbe809e84c11edf053dcf16a9f6304.PubTator"}
2025-07-16 22:33:29,894 - INFO - Connection accepted from ('127.0.0.1', 51160)
2025-07-16 22:33:29,894 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "6c9ce2824b187646d864962dc8d8875097e553b032c259364b47c8e4.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 276.71it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 29662.69it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 5255.36it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 4971.32it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 144.77it/s]
2025-08-03 19:25:52,369 - INFO - Server started on localhost:18783
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 24272.59it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 3015.32it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 188.93it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 27962.03it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 12830.54it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 5985.02it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 11110.74it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 8395.32it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 24357.17it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 86659.17it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 6990.51it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 36695.57it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 31000.03it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 20540.18it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 13893.02it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 31631.25it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
/home/mabdallah/.conda/envs/trialmatchai/lib/python3.11/site-packages/torch/cuda/__init__.py:182: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 151418.92it/s]
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 4355.91it/s]
2025-08-03 19:48:24,006 - INFO - Server started on localhost:18783
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 790.44it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 19293.03it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-03 19:53:26,698 - INFO - Connection accepted from ('127.0.0.1', 45486)
2025-08-03 19:53:26,698 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "2dfc5be0d0231979e69390328155926f65b2e97e59a1eeec9eb31e73.PubTator"}
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
2025-08-03 19:54:22,242 - INFO - Connection accepted from ('127.0.0.1', 38496)
2025-08-03 19:54:22,242 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "db7442428d1dd92f798475bc173d0b523bdd022963e7e0eff5ff05a7.PubTator"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 10205.12it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 31920.12it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-03 21:36:00,079 - INFO - Connection accepted from ('127.0.0.1', 53320)
2025-08-03 21:36:00,080 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "57c274e89711aee0e215c55ce2570826468ebf80104f04b418e79b23.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 21542.39it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 16150.57it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-03 21:39:12,257 - INFO - Connection accepted from ('127.0.0.1', 50288)
2025-08-03 21:39:12,257 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "0fb7e7924a0c2b8724b4b5d94aacd0e7bfbc6f6e1214b83b0d11d208.PubTator"}
2025-08-03 21:41:36,886 - INFO - Connection accepted from ('127.0.0.1', 36174)
2025-08-03 21:41:36,886 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "a09149cbf48d3f07b7ce16a02353412a74ffb11fb57d4416c27c58a9.PubTator"}
                                                                                                                                                                                                                                                                                                                                                                                       Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 9362.29it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 20825.74it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 24357.17it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 19663.87it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 3795.75it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 6159.04it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 54684.54it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 16844.59it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 11002.90it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 63840.24it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-03 22:10:08,491 - INFO - Connection accepted from ('127.0.0.1', 46522)
2025-08-03 22:10:08,491 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "027e65fb2b9483bcd3c217013c9b445f4e8d55b2abc47edefdd6a9cd.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 13387.50it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 19187.12it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-18 15:28:06,176 - INFO - Connection accepted from ('127.0.0.1', 58716)
2025-08-18 15:28:06,176 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 14889.26it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 41323.19it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-18 15:29:11,198 - INFO - Connection accepted from ('127.0.0.1', 36608)
2025-08-18 15:29:11,199 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 24936.41it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 13631.15it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 153.12it/s]
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 681.42it/s]
2025-08-18 15:41:39,806 - INFO - Server started on localhost:18783
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-19 15:34:24,184 - INFO - Connection accepted from ('127.0.0.1', 43682)
2025-08-19 15:34:24,184 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 203.01it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 21833.96it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 4395.16it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 9308.26it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-19 15:38:56,174 - INFO - Connection accepted from ('127.0.0.1', 47184)
2025-08-19 15:38:56,174 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "99151b7a67a22ab55f38dd2a06a3d775da819ea5d446a03adda90b14.PubTator"}
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
2025-08-19 15:39:26,523 - INFO - Connection accepted from ('127.0.0.1', 59158)
2025-08-19 15:39:26,523 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "fb70ddb214ae646af6262f0d81f16392aea2d1c51d135bdc5ef78115.PubTator"}
2025-08-19 16:01:53,270 - INFO - Connection accepted from ('127.0.0.1', 35774)
2025-08-19 16:01:53,271 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "d13f07266a57d3b9ba73f0a0c9a21408eaf190b110eeb44776863fe8.PubTator"}
2025-08-19 16:02:20,147 - INFO - Connection accepted from ('127.0.0.1', 35438)
2025-08-19 16:02:20,147 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "6d60d5573378fb2ca71a90099fe304ec4d5532cafebec4676f42fe28.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 154.16it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 11500.70it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 15420.24it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 22322.00it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 3908.59it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 8279.32it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 7226.57it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 159479.24it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 5419.70it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 16461.16it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-19 16:16:17,634 - INFO - Connection accepted from ('127.0.0.1', 32956)
2025-08-19 16:16:17,634 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 9526.01it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 135737.99it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 11202.74it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 27413.75it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 11052.18it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 11011.56it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 7174.66it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 23431.87it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-19 16:30:35,460 - INFO - Connection accepted from ('127.0.0.1', 41266)
2025-08-19 16:30:35,461 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 11229.73it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 24877.25it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-19 16:31:13,964 - INFO - Connection accepted from ('127.0.0.1', 34758)
2025-08-19 16:31:13,964 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "3e4cb8e7df26c985018bd8c25b5efa344c861af6fe4929e3d910128a.PubTator"}
2025-08-19 16:31:37,998 - INFO - Connection accepted from ('127.0.0.1', 60472)
2025-08-19 16:31:37,998 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "e255e7d010331dabb92a4c12029f2fa1f3080eabb86ec5c7bcd14326.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 12221.17it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 21765.98it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-19 16:34:04,689 - INFO - Connection accepted from ('127.0.0.1', 45688)
2025-08-19 16:34:04,689 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 5562.74it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 7672.04it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-19 16:35:00,735 - INFO - Connection accepted from ('127.0.0.1', 45280)
2025-08-19 16:35:00,735 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "a1f93c97c4fa3a0e9c279be4d49a56bef290b4242e0e72b792d607b4.PubTator"}
2025-08-19 16:35:21,595 - INFO - Connection accepted from ('127.0.0.1', 57028)
2025-08-19 16:35:21,595 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "643bdfe9af48c14c2eca0ae9b39b15d57e78077cc70e3df07d888f1f.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 123.13it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 44197.09it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-21 18:43:14,684 - INFO - Connection accepted from ('127.0.0.1', 36790)
2025-08-21 18:43:14,684 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "7bbf3bbb6ce76096d9fbc4afcf95b756696944eb3970d9ae79a453c2.PubTator"}
2025-08-21 20:28:07,171 - INFO - Connection accepted from ('127.0.0.1', 46510)
2025-08-21 20:28:07,171 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "427736011957cbb0ce549f492b0330b9d77ba984a2beb7b2abca8453.PubTator"}
2025-08-21 20:28:26,150 - INFO - Connection accepted from ('127.0.0.1', 43538)
2025-08-21 20:28:26,151 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "cd52dd424cb42cb53d92271bdd29ee9d3fa8bda53b90517a830f3685.PubTator"}
2025-08-21 20:28:40,788 - INFO - Connection accepted from ('127.0.0.1', 59882)
2025-08-21 20:28:40,788 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "f5103ff8dd9ca435775ae888a3777ff367e7d2bf988b746c61e21cd9.PubTator"}
2025-08-21 20:28:55,052 - INFO - Connection accepted from ('127.0.0.1', 39820)
2025-08-21 20:28:55,052 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "9471c3496c72a025b12c32c03e254c54fd34a88ad8c5d467920db40e.PubTator"}
2025-08-21 20:29:09,787 - INFO - Connection accepted from ('127.0.0.1', 44720)
2025-08-21 20:29:09,787 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "1cd9760fe682423e9e3c37d70f3e932d45259c7c9d4b6e911fbf9b42.PubTator"}
2025-08-21 20:29:22,596 - INFO - Connection accepted from ('127.0.0.1', 50796)
2025-08-21 20:29:22,596 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "7c24cb8cc3a7c35ca168b66e94c7cc0f7233f362f69b08c9b60eb758.PubTator"}
2025-08-21 20:29:34,137 - INFO - Connection accepted from ('127.0.0.1', 55958)
2025-08-21 20:29:34,137 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "b4364ea1aa7c138ce56345794e8201b25ccddbceccc3a0a6699f7c0f.PubTator"}
2025-08-21 20:29:46,982 - INFO - Connection accepted from ('127.0.0.1', 54484)
2025-08-21 20:29:46,982 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "cc07129a14bc136b9fb4a3ab01ea61864fe49f0dc442b3ed29a8b62c.PubTator"}
2025-08-21 20:29:58,469 - INFO - Connection accepted from ('127.0.0.1', 42424)
2025-08-21 20:29:58,470 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "bbdc029db533f0cb0bd9ec2c28ec49703dcefdf858055062923a1e04.PubTator"}
2025-08-21 20:30:08,477 - INFO - Connection accepted from ('127.0.0.1', 45430)
2025-08-21 20:30:08,477 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "f543f4f8e42327abe82c5c3874536c4fb9438e1a76c0a630198fe2d7.PubTator"}
2025-08-21 20:30:19,554 - INFO - Connection accepted from ('127.0.0.1', 38528)
2025-08-21 20:30:19,554 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "120898529785ace80a90c6a34477b0497c91621b8aa67e5a6b22f0f3.PubTator"}
2025-08-21 20:30:28,083 - INFO - Connection accepted from ('127.0.0.1', 38538)
2025-08-21 20:30:28,084 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "a863b4c155212c13c6dc7b78a66dbadc236150e5854e7ad6dafd3c34.PubTator"}
2025-08-21 20:30:36,949 - INFO - Connection accepted from ('127.0.0.1', 58148)
2025-08-21 20:30:36,949 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "dfea813b5bf039b384ac104cc18a0547dff18dd604ea71d23f3d9e23.PubTator"}
2025-08-21 20:30:45,521 - INFO - Connection accepted from ('127.0.0.1', 50946)
2025-08-21 20:30:45,521 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "19bd08e9f22e6c3824f7bacb49b915819c73f1972dfcb32283cea9f6.PubTator"}
2025-08-21 20:30:54,051 - INFO - Connection accepted from ('127.0.0.1', 39230)
2025-08-21 20:30:54,051 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "5d226bcff34bb0ebfad070b6b566113f06c2a61fb5c4e5e0e3a04554.PubTator"}
2025-08-21 20:30:59,151 - INFO - Connection accepted from ('127.0.0.1', 39240)
2025-08-21 20:30:59,151 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "ebc30fd8256840a29eb3943a8246dc7eea3f636de4c5f71631f8aab6.PubTator"}
2025-08-21 20:31:06,592 - INFO - Connection accepted from ('127.0.0.1', 54862)
2025-08-21 20:31:06,592 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "30ff7bb0e9d02c0fd0b0054a9d618d25662339cafc3fcc1442c57182.PubTator"}
2025-08-21 20:31:11,283 - INFO - Connection accepted from ('127.0.0.1', 52380)
2025-08-21 20:31:11,283 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "3c499812cd51602e41f4687d1cf95e54a180f6bac1766a346fa82fb4.PubTator"}
2025-08-21 20:31:17,381 - INFO - Connection accepted from ('127.0.0.1', 52390)
2025-08-21 20:31:17,382 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "47cc34dc232a359bd7aaa4bbf9bd33d9d01ea390f670ec15243ce95e.PubTator"}
2025-08-21 20:31:24,416 - INFO - Connection accepted from ('127.0.0.1', 38594)
2025-08-21 20:31:24,416 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "e45ed29fce772186ef533ec31f2161005b7e984dc629bb734fb5b9c8.PubTator"}
2025-08-21 20:31:41,790 - INFO - Connection accepted from ('127.0.0.1', 33734)
2025-08-21 20:31:41,790 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "a7a921dccee50b85b93ac89251a0403a566783176a94880b1844daf2.PubTator"}
2025-08-21 20:31:50,234 - INFO - Connection accepted from ('127.0.0.1', 39546)
2025-08-21 20:31:50,235 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "f99bca598e5bacb24920109bfe16f52a4adcf0623e42f5f35446745b.PubTator"}
2025-08-21 20:31:57,679 - INFO - Connection accepted from ('127.0.0.1', 39558)
2025-08-21 20:31:57,680 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "96fe8a6afa86d95762b56396c5e85bdba1691a5a3d2511612ee22e5e.PubTator"}
2025-08-21 20:32:02,583 - INFO - Connection accepted from ('127.0.0.1', 34198)
2025-08-21 20:32:02,583 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "84f4d162d0889536a392b46f32eebda58db27e58561a3e41e33e4cea.PubTator"}
2025-08-21 20:32:11,222 - INFO - Connection accepted from ('127.0.0.1', 52042)
2025-08-21 20:32:11,222 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "afc3d09d59021579b48e4819dd3f08295f3dc438f7f2919b06ca317e.PubTator"}
2025-08-21 20:32:17,541 - INFO - Connection accepted from ('127.0.0.1', 52046)
2025-08-21 20:32:17,541 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "525bbc5e481bdaf825bf80725e1ac63c15786fa13120fe734d703c0e.PubTator"}
2025-08-21 20:32:27,493 - INFO - Connection accepted from ('127.0.0.1', 49636)
2025-08-21 20:32:27,493 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "89e92a6963f2179038668173907fc2a79ae48e7712fe3dddfe49dace.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 7933.24it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 23314.64it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 9216.23it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 10549.05it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               2025-08-21 21:12:10,136 - INFO - Connection accepted from ('127.0.0.1', 37164)
2025-08-21 21:12:10,137 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 11060.93it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 22017.34it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-21 21:12:47,785 - INFO - Connection accepted from ('127.0.0.1', 58406)
2025-08-21 21:12:47,785 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "7aed0d619cfb7fb7edf932fc5aeff01e489c3be8482e4c08c26f4de3.PubTator"}
2025-08-21 21:12:56,082 - INFO - Connection accepted from ('127.0.0.1', 44096)
2025-08-21 21:12:56,082 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "033058d4b744c965cb1f7c798cc9c1fee136688c7bdd6f191929cd02.PubTator"}
2025-08-21 21:13:08,785 - INFO - Connection accepted from ('127.0.0.1', 38616)
2025-08-21 21:13:08,785 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "dc37d57b5508811be20af120757571a6a7725f0d2977f58c84837a7f.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 9567.30it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 23710.03it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 3965.87it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 5995.29it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-21 21:29:46,644 - INFO - Connection accepted from ('127.0.0.1', 47556)
2025-08-21 21:29:46,644 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "729d3f9975787183c5117b5f2a4604e97594352b40aaf9e3688a6823.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 4296.12it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 12694.62it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-21 21:51:03,365 - INFO - Connection accepted from ('127.0.0.1', 37414)
2025-08-21 21:51:03,365 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 24628.91it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files:  80%|████████  | 8/10 [00:00<00:00, 39.37it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 49.16it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 5751.93it/s]
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 17396.53it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 10829.60it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 23288.75it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-21 21:56:53,487 - INFO - Connection accepted from ('127.0.0.1', 43622)
2025-08-21 21:56:53,487 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "37f8a68ed3c820c1c408bb453ec7114e791811a377460d41c3c3ea84.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 9198.04it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 4601.54it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-21 22:05:42,823 - INFO - Connection accepted from ('127.0.0.1', 35540)
2025-08-21 22:05:42,823 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "801077202e18420c5835e270c0d90333911485e69e231121751d3032.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 4754.37it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 11956.40it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-21 22:08:51,047 - INFO - Connection accepted from ('127.0.0.1', 49732)
2025-08-21 22:08:51,048 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 10140.97it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 21215.50it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-21 22:11:08,274 - INFO - Connection accepted from ('127.0.0.1', 48154)
2025-08-21 22:11:08,275 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 12603.08it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 19472.16it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-21 22:11:46,268 - INFO - Connection accepted from ('127.0.0.1', 52076)
2025-08-21 22:11:46,268 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "69f6719bd150439e24005d8432c68e39bf31d5fc113a028bfbd91006.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 20001.45it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 14478.09it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-21 22:35:00,501 - INFO - Connection accepted from ('127.0.0.1', 48388)
2025-08-21 22:35:00,501 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "fafdb99975801684a412340ad98293cfe2307e3ab3d7ff0c006eeda5.PubTator"}
2025-08-21 23:44:59,511 - INFO - Connection accepted from ('127.0.0.1', 43480)
2025-08-21 23:44:59,511 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "a0b53db8b2ef91d1ebe9d88002d924aca9ec237b144275572593c32e.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 4431.85it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 25404.63it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-21 23:56:24,624 - INFO - Connection accepted from ('127.0.0.1', 45490)
2025-08-21 23:56:24,624 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "d48beeca8a07e4059a6bea41aad1a8b7e85c15a578008e7317717b07.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 11388.28it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 95108.93it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-22 00:13:33,851 - INFO - Connection accepted from ('127.0.0.1', 41250)
2025-08-22 00:13:33,851 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "c3ea6a29dbea4a139d96f6135c9c1ddd85a1925ab6b64c8658723b5e.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 15905.59it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 43509.38it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-22 00:18:18,681 - INFO - Connection accepted from ('127.0.0.1', 55022)
2025-08-22 00:18:18,682 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "44b8882bc774b330ebd400912695dfee5bd544e2050be5c5ead326ca.PubTator"}
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 15363.75it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 6853.44it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-22 00:27:32,174 - INFO - Connection accepted from ('127.0.0.1', 45592)
2025-08-22 00:27:32,174 - INFO - Received data: {"biomedner_home": "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser", "inputfile": "5022147668ee40f2c64fbef14833893a7356260f54b8b279698a6462.PubTator"}
2025-08-22 00:31:53,330 - INFO - Connection accepted from ('127.0.0.1', 58504)
2025-08-22 00:31:53,330 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 8985.23it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 25543.87it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
2025-08-22 00:33:50,052 - INFO - Connection accepted from ('127.0.0.1', 53190)
2025-08-22 00:33:50,053 - ERROR - An error occurred: unpack requires a buffer of 2 bytes
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 6059.38it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 4355.00it/s]
Traceback (most recent call last):
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 206, in <module>
    run_server(mt_ner, args)
  File "/nfs/scratch/mabdallah/TrialMatchAI/source/Parser/gner_server.py", line 177, in run_server
    s.bind((host, port))
OSError: [Errno 98] Address already in use
